### PR TITLE
FIX: Require bz2file and six

### PR DESCRIPTION
**Pull request by effigies**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Addresses nipy/nibabel#710.

### CODE REVIEW

**Comment by effigies** [comment]
@conda-forge-admin, please rerender

**Comment by effigies** [comment]
@conda-forge-admin, please rerender

**Comment by effigies** [comment]
TBH, I'm not sure what to make of this. @matthew-brett, have you run into a Windows installation error like:

`Could not install packages due to an EnvironmentError: [('C:\\bld\\nibabel_1546970579482\\work\\doc\\downloads', 'c:\\users\\appveyor\\appdata\\local\\temp\\1\\pip-req-build-0kqlfk\\doc\\downloads', "[Errno 22] invalid mode ('rb') or filename: 'C:\\\\bld\\\\nibabel_1546970579482\\\\work\\\\doc\\\\downloads'"), ('C:\\bld\\nibabel_1546970579482\\work\\doc\\source\\changelog.rst', 'c:\\users\\appveyor\\appdata\\local\\temp\\1\\pip-req-build-0kqlfk\\doc\\source\\changelog.rst', "[Errno 22] invalid mode ('rb') or filename: 'C:\\\\bld\\\\nibabel_1546970579482\\\\work\\\\doc\\\\source\\\\changelog.rst'"), ('C:\\bld\\nibabel_1546970579482\\work\\doc\\source\\legal.rst', 'c:\\users\\appveyor\\appdata\\local\\temp\\1\\pip-req-build-0kqlfk\\doc\\source\\legal.rst', "[Errno 22] invalid mode ('rb') or filename: 'C:\\\\bld\\\\nibabel_1546970579482\\\\work\\\\doc\\\\source\\\\legal.rst'")]`

**Comment by matthew-brett** [comment]
No, sorry, I never seen anything like that - but I very rarely use conda...

**Comment by effigies** [comment]
@conda-forge-admin please rerender.

**Comment by effigies** [comment]
Looks like this is held up by conda-forge/conda-smithy#1002

**Comment by grlee77** [comment]
> Looks like this is held up by conda-forge/conda-smithy#1002

I wonder if changing the source section to checkout from the repo might work as a temporary workaround?:
e.g..
```yaml
source:
  git_url: https://github.com/nipy/nibabel.git
  git_tag: {{ version }}
```
I think the symbolic link will just end up as an empty file in that case which may avoid the issues seen here.

**Comment by effigies** [comment]
From [the docs](https://conda-forge.org/docs/meta.html):

> Conda-forge requires that building from tarballs using the url and fn keys in the build section. A recipe should not use the git_url, git_ver, and similar keys.

**Comment by effigies** [comment]
I think the easiest solution will be just to add the `bz2file` dependency without any requirement for Python 2, and revert to `noarch`. Then the builds happen on Linux, and we don't hit this annoying Windows case. If they fix archive extraction on Windows in the future, we can bump the build number for any 2.3.2+ packages.

What do y'all think?

**Comment by grlee77** [comment]
Yeah, I think that is a good option.  Particularly since it looks like bz2file is only around 8kb in size, so not a substantial burden in download size, etc.

**Pull request merged**
