### PR TITLE
 ENH: Enable Python 3.7 compilation 

### PR DESCRIPTION
**Pull request by effigies**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Piggybacking on #14.

Closes #14.

### CODE REVIEW

**Comment by effigies** [comment]
@conda-forge-admin, please rerender

**Comment by grlee77** [comment]
I think you have to add a line containing 
`max_py_ver: '37'`

to `conda-forge.yml` and then rerender to trigger the Python 3.7 build.

**Comment by effigies** [comment]
I thought the only thing we fiddled with was `recipe/meta.yml`. But whenever I've seen these PRs from the bot, the initial change and rerendering were done in a single commit.

**Comment by grlee77** [comment]
I have seen the conda-forge team recommend adding this line:
https://github.com/conda-forge/conda-forge.github.io/issues/649#issuecomment-423543591

**Comment by grlee77** [comment]
I guess this repo never got a PR from the bot because it was marked `noarch`. I'm not sure if the bot would find and auto-generate a PR to add 3.7 if we were to merge one of these PRs removing noarch.

**Comment by effigies** [comment]
@conda-forge-admin, please rerender

**Comment by effigies** [comment]
Gotcha. That makes sense. Thanks for looking into that.

**Pull request closed without merging**
